# This is a basic workflow to help you get started with Actions

name: Royal Tux

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Emperor"
  Emperor:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Authorize publickey
        run: |
          echo "Authorizing publickey for the user: $(whoami)"
          mkdir -p ~/.ssh
          echo ${{ secrets.PUBLICKEY }} >> ~/.ssh/authorized_keys
          mkdir -p ~/.nx/config
          echo ${{ secrets.PUBLICKEY }} >> ~/.nx/config/authorized.crt
          chmod 0600 ~/.nx/config/authorized.crt

      - name: Setup Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup Desktop
        run: |
          sudo apt update
          sudo apt install ubuntu-desktop-minimal -y

      - name: Setup NX Server
        run: |
          wget https://download.nomachine.com/download/8.2/Linux/nomachine_8.2.3_4_amd64.deb
          sudo apt install ./nomachine_8.2.3_4_amd64.deb -y
          rm ./nomachine_8.2.3_4_amd64.deb

      - name: Sleep
        run: sleep 355m
