# This is a basic workflow to help you get started with Actions

name: Royal Tux

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "runner"
  runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Reset User Password
        run: |
          sudo usermod --password $(openssl passwd -6 '$(whoami)') $(whoami)

      - name: Setup Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
          
      - name: Setup Desktop
        run: |
          sudo apt update
          sudo apt install ubuntu-mate-desktop xrdp -y
          sudo ufw allow 3389
          sudo systemctl start xrdp

      - name: Set User Key
        run: |
          whoami
          # mkdir -p ~/.ssh
          # echo ${{ secrets.PUBLIC_KEY }} >> ~/.ssh/authorized_keys 

      - name: Sleep
        run: sleep 359m
