# This is a basic workflow to help you get started with Actions

name: Darwin

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "runner"
  runner:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Tailscale
        run: |
          go env -w GO111MODULE=off
          GOPATH=${GOPATH:-~/go}
          export PATH="${PATH}:${GOPATH}/bin"
          go install tailscale.com/cmd/tailscale{,d}@main
          sudo tailscaled install-system-daemon
          sudo tailscale up

      - name: Authorize publickey
        run: |
          whoami
          mkdir -p ~/.ssh
          echo ${{ secrets.PUBLICKEY }} >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          sudo su root -c 'echo "PasswordAuthentication no" >> /etc/ssh/sshd_config'
          sudo su root -c 'echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config'
          sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

      - name: Sleep
        run: sleep 21540
